
# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
r:
  - oldrel
  - release
  - devel
sudo: required
warnings_are_errors: true
before_install:
- sudo apt-get -qq update
cache: packages
r_packages: 
  - testthat
  - roxygen2
  - methods
after_success:
  - Rscript -e 'devtools::install();devtools::test()'
  - Rscript -e 'covr::coveralls()'
